default:
  type: mysql
  host: rdb
  port: 3306
  username: root
  password: root
  database: app_db
  synchronize: true
  entities:
    - dist/entities/**/*.entity.js
  migrations:
    - dist/migrations/**/*.js
  logging: true